import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    include: ["src/**/*.test.ts"],
    exclude: ["src/test/**"],
    pool: "threads",
    testTimeout: 30_000,
    coverage: {
      provider: "v8",
      reporter: ["text", "html", "lcov"],
      include: ["src/**/*.ts"],
      exclude: [
        "src/**/*.test.ts",
        "src/test/**",
        "src/cli.ts",
        "src/auth/local-login.ts",
        "src/auth/substack-login.ts",
        "src/browser/**",
        "src/doctor/doctor.ts",
        "src/mcp/catalog.ts",
        "src/mcp/prompts.ts",
        "src/mcp/resources.ts",
        "src/mcp/server.ts",
        "src/substack-api/auth.ts",
        "src/substack-api/analytics.ts",
        "src/substack-api/billing.ts",
        "src/substack-api/client.ts",
        "src/substack-api/draft-inspect.ts",
        "src/substack-api/draft-lookup.ts",
        "src/substack-api/draft-section.ts",
        "src/substack-api/draft-write.ts",
        "src/substack-api/email.ts",
        "src/substack-api/integrations.ts",
        "src/substack-api/media-upload.ts",
        "src/substack-api/podcast.ts",
        "src/substack-api/publish-write.ts",
        "src/substack-api/publication-settings.ts",
        "src/substack-api/read-model.ts",
        "src/publish/browser-workflow.ts",
        "src/publish/local-workflow.ts",
      ],
      thresholds: {
        statements: 91,
        branches: 91,
        functions: 91,
        lines: 91,
      },
    },
  },
});
