#!/usr/bin/env bash
# Source this file from bash or zsh to load completions generated by the
# installed substack-cli binary. Static completion files are not shipped.

if ! command -v substack-cli > /dev/null 2>&1; then
  echo "substack-cli is not on PATH; install @edithatogo/substack-cli first." >&2
  return 1 2> /dev/null || exit 1
fi

if [ -n "${ZSH_VERSION:-}" ]; then
  source <(substack-cli completion zsh)
elif [ -n "${BASH_VERSION:-}" ]; then
  source <(substack-cli completion bash)
else
  echo "Unsupported shell. Use bash, zsh, or 'substack-cli completion <shell>' directly." >&2
  return 1 2> /dev/null || exit 1
fi
