# Register PowerShell completions generated by the installed substack-cli binary.
# Static completion files are not shipped; dot-source this file from $PROFILE.

if (-not (Get-Command substack-cli -ErrorAction SilentlyContinue)) {
    Write-Error "substack-cli is not on PATH; install @edithatogo/substack-cli first."
    return
}

$script:substackCliCompletions = substack-cli completion powershell

Register-ArgumentCompleter -Native -CommandName substack-cli -ScriptBlock {
    param($wordToComplete, $commandAst, $cursorPosition)

    $script:substackCliCompletions |
        Where-Object { $_ -like "$wordToComplete*" } |
        ForEach-Object {
            [System.Management.Automation.CompletionResult]::new($_, $_, "ParameterValue", $_)
        }
}
